baseURL = 'https://hang.swiftzer.net/'
languageCode = 'en-us'
title = 'TUSK'
theme = "hello-friend"
paginate = 5
googleAnalytics = 'G-J3XEEH0Q63'

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "TUSK"
    subtitle = "Watching things with another angle"
    keywords = "Felix,Blog,Hugo"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "TUSK"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "category"
        name = "Category"
        url = "/categories"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/hongkongfelix"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "flickr"
        name = "Flickr"
        url = "https://www.flickr.com/felix-chan/"
        weight = 5